//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CashCenter.Objective.HotWater
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotWaterCustomer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HotWaterCustomer()
        {
            this.HotWaterPayments = new HashSet<HotWaterPayment>();
        }
    
        public int Id { get; set; }
        public int Number { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string TimePeriodCode { get; set; }
        public decimal TotalForPay { get; set; }
        public string CounterName1 { get; set; }
        public double CounterValue1 { get; set; }
        public string CounterName2 { get; set; }
        public double CounterValue2 { get; set; }
        public string CounterName3 { get; set; }
        public double CounterValue3 { get; set; }
        public string CounterName4 { get; set; }
        public double CounterValue4 { get; set; }
        public string CounterName5 { get; set; }
        public double CounterValue5 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HotWaterPayment> HotWaterPayments { get; set; }
    }
}
