//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CashCenter.Objective.HotWater
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotWaterPayment
    {
        public int Id { get; set; }
        public int CustomerId { get; set; }
        public System.DateTime CreateDate { get; set; }
        public decimal Total { get; set; }
        public decimal CommisionTotal { get; set; }
        public double NewCounterValue1 { get; set; }
        public double NewCounterValue2 { get; set; }
        public double NewCounterValue3 { get; set; }
        public double NewCounterValue4 { get; set; }
        public double NewCounterValue5 { get; set; }
        public string Description { get; set; }
    
        public virtual HotWaterCustomer HotWaterCustomer { get; set; }
    }
}
