INSERT INTO [dbo].[Region] ([Id], [Name]) VALUES (0, N'Верхний Ландех')
INSERT INTO [dbo].[Region] ([Id], [Name]) VALUES (1, N'Вичуга')
INSERT INTO [dbo].[Region] ([Id], [Name]) VALUES (2, N'Гаврилов Посад')
INSERT INTO [dbo].[Region] ([Id], [Name]) VALUES (4, N'Заволжск')
INSERT INTO [dbo].[Region] ([Id], [Name]) VALUES (6, N'Кохма')
INSERT INTO [dbo].[Region] ([Id], [Name]) VALUES (9, N'Кинешма')
INSERT INTO [dbo].[Region] ([Id], [Name]) VALUES (11, N'Комсомольск')
INSERT INTO [dbo].[Region] ([Id], [Name]) VALUES (13, N'Лежнево')
INSERT INTO [dbo].[Region] ([Id], [Name]) VALUES (14, N'Наволоки')
INSERT INTO [dbo].[Region] ([Id], [Name]) VALUES (15, N'Палех')
INSERT INTO [dbo].[Region] ([Id], [Name]) VALUES (16, N'Пестяки')
INSERT INTO [dbo].[Region] ([Id], [Name]) VALUES (17, N'Приволжск')
INSERT INTO [dbo].[Region] ([Id], [Name]) VALUES (18, N'Плёс')
INSERT INTO [dbo].[Region] ([Id], [Name]) VALUES (19, N'Пучеж')
INSERT INTO [dbo].[Region] ([Id], [Name]) VALUES (20, N'Родники')
INSERT INTO [dbo].[Region] ([Id], [Name]) VALUES (21, N'Тейково')
INSERT INTO [dbo].[Region] ([Id], [Name]) VALUES (24, N'Фурманов')
INSERT INTO [dbo].[Region] ([Id], [Name]) VALUES (27, N'Шуя')
INSERT INTO [dbo].[Region] ([Id], [Name]) VALUES (31, N'Южа')
INSERT INTO [dbo].[Region] ([Id], [Name]) VALUES (32, N'Юрьевец')
INSERT INTO [dbo].[Region] ([Id], [Name]) VALUES (34, N'Савино')
INSERT INTO [dbo].[Region] ([Id], [Name]) VALUES (100, N'ТЕСТ')

SET IDENTITY_INSERT [dbo].[Department] ON
INSERT INTO [dbo].[Department] ([Id], [Code], [Name], [RegionId], [Url], [Path]) VALUES (1, N'0001', N'', 0)
INSERT INTO [dbo].[Department] ([Id], [Code], [Name], [RegionId], [Url], [Path]) VALUES (4, N'0002', N'', 1)
INSERT INTO [dbo].[Department] ([Id], [Code], [Name], [RegionId], [Url], [Path]) VALUES (5, N'0003', N'', 1)
INSERT INTO [dbo].[Department] ([Id], [Code], [Name], [RegionId], [Url], [Path]) VALUES (6, N'0004', N'', 2)
INSERT INTO [dbo].[Department] ([Id], [Code], [Name], [RegionId], [Url], [Path]) VALUES (7, N'0005', N'', 2)
INSERT INTO [dbo].[Department] ([Id], [Code], [Name], [RegionId], [Url], [Path]) VALUES (8, N'0006', N'', 4)
INSERT INTO [dbo].[Department] ([Id], [Code], [Name], [RegionId], [Url], [Path]) VALUES (10, N'0007', N'', 4)
INSERT INTO [dbo].[Department] ([Id], [Code], [Name], [RegionId], [Url], [Path]) VALUES (11, N'0020', N'Кохма', 6)
INSERT INTO [dbo].[Department] ([Id], [Code], [Name], [RegionId], [Url], [Path]) VALUES (13, N'0010', N'Ивановский р-н', 6)
INSERT INTO [dbo].[Department] ([Id], [Code], [Name], [RegionId], [Url], [Path]) VALUES (14, N'0020', N'ЖКХ', 6)
INSERT INTO [dbo].[Department] ([Id], [Code], [Name], [RegionId], [Url], [Path]) VALUES (16, N'0020', N'КУК', 6)
INSERT INTO [dbo].[Department] ([Id], [Code], [Name], [RegionId], [Url], [Path]) VALUES (17, N'0012', N'', 9)
INSERT INTO [dbo].[Department] ([Id], [Code], [Name], [RegionId], [Url], [Path]) VALUES (18, N'0013', N'', 9)
INSERT INTO [dbo].[Department] ([Id], [Code], [Name], [RegionId], [Url], [Path]) VALUES (20, N'0014', N'', 11)
INSERT INTO [dbo].[Department] ([Id], [Code], [Name], [RegionId], [Url], [Path]) VALUES (21, N'0015', N'', 11)
INSERT INTO [dbo].[Department] ([Id], [Code], [Name], [RegionId], [Url], [Path]) VALUES (22, N'0016', N'', 13)
INSERT INTO [dbo].[Department] ([Id], [Code], [Name], [RegionId], [Url], [Path]) VALUES (23, N'0017', N'', 14)
INSERT INTO [dbo].[Department] ([Id], [Code], [Name], [RegionId], [Url], [Path]) VALUES (24, N'0018', N'', 15)
INSERT INTO [dbo].[Department] ([Id], [Code], [Name], [RegionId], [Url], [Path]) VALUES (25, N'0019', N'', 16)
INSERT INTO [dbo].[Department] ([Id], [Code], [Name], [RegionId], [Url], [Path]) VALUES (26, N'0020', N'', 17)
INSERT INTO [dbo].[Department] ([Id], [Code], [Name], [RegionId], [Url], [Path]) VALUES (27, N'0021', N'', 18)
INSERT INTO [dbo].[Department] ([Id], [Code], [Name], [RegionId], [Url], [Path]) VALUES (28, N'0022', N'', 19)
INSERT INTO [dbo].[Department] ([Id], [Code], [Name], [RegionId], [Url], [Path]) VALUES (29, N'0023', N'', 20)
INSERT INTO [dbo].[Department] ([Id], [Code], [Name], [RegionId], [Url], [Path]) VALUES (30, N'0024', N'', 21)
INSERT INTO [dbo].[Department] ([Id], [Code], [Name], [RegionId], [Url], [Path]) VALUES (31, N'0025', N'', 21)
INSERT INTO [dbo].[Department] ([Id], [Code], [Name], [RegionId], [Url], [Path]) VALUES (32, N'0026', N'', 21)
INSERT INTO [dbo].[Department] ([Id], [Code], [Name], [RegionId], [Url], [Path]) VALUES (33, N'0027', N'', 24)
INSERT INTO [dbo].[Department] ([Id], [Code], [Name], [RegionId], [Url], [Path]) VALUES (34, N'0028', N'', 24)
INSERT INTO [dbo].[Department] ([Id], [Code], [Name], [RegionId], [Url], [Path]) VALUES (35, N'0029', N'', 24)
INSERT INTO [dbo].[Department] ([Id], [Code], [Name], [RegionId], [Url], [Path]) VALUES (36, N'0030', N'', 27)
INSERT INTO [dbo].[Department] ([Id], [Code], [Name], [RegionId], [Url], [Path]) VALUES (37, N'0031', N'', 27)
INSERT INTO [dbo].[Department] ([Id], [Code], [Name], [RegionId], [Url], [Path]) VALUES (38, N'0032', N'', 27)
INSERT INTO [dbo].[Department] ([Id], [Code], [Name], [RegionId], [Url], [Path]) VALUES (39, N'0033', N'', 27)
INSERT INTO [dbo].[Department] ([Id], [Code], [Name], [RegionId], [Url], [Path]) VALUES (40, N'0034', N'', 31)
INSERT INTO [dbo].[Department] ([Id], [Code], [Name], [RegionId], [Url], [Path]) VALUES (41, N'0035', N'', 32)
INSERT INTO [dbo].[Department] ([Id], [Code], [Name], [RegionId], [Url], [Path]) VALUES (42, N'0036', N'', 32)
INSERT INTO [dbo].[Department] ([Id], [Code], [Name], [RegionId], [Url], [Path]) VALUES (43, N'0037', N'', 34)
INSERT INTO [dbo].[Department] ([Id], [Code], [Name], [RegionId], [Url], [Path]) VALUES (44, N'00000', N'Лежнево', 100)
INSERT INTO [dbo].[Department] ([Id], [Code], [Name], [RegionId], [Url], [Path]) VALUES (45, N'00001', N'Кохма', 100)
INSERT INTO [dbo].[Department] ([Id], [Code], [Name], [RegionId], [Url], [Path]) VALUES (47, N'00002', N'Кохма тест', 100)
SET IDENTITY_INSERT [dbo].[Department] OFF

SET IDENTITY_INSERT [dbo].[ArticlePriceType] ON
INSERT INTO [dbo].[ArticlePriceType] ([Id], [Name], [IsDefault], [IsWholesale], [Code]) VALUES (4, N'Розничная цена', 1, 0, N'00001')
INSERT INTO [dbo].[ArticlePriceType] ([Id], [Name], [IsDefault], [IsWholesale], [Code]) VALUES (5, N'Цена для сотрудников компании', 0, 0, N'00002')
INSERT INTO [dbo].[ArticlePriceType] ([Id], [Name], [IsDefault], [IsWholesale], [Code]) VALUES (7, N'Цена при оптовой закупке', 0, 1, N'00003')
INSERT INTO [dbo].[ArticlePriceType] ([Id], [Name], [IsDefault], [IsWholesale], [Code]) VALUES (8, N'Цена при реализации через сеть Интернет', 0, 0, N'00004')
INSERT INTO [dbo].[ArticlePriceType] ([Id], [Name], [IsDefault], [IsWholesale], [Code]) VALUES (9, N'Цена по акции', 0, 0, N'00005')
SET IDENTITY_INSERT [dbo].[ArticlePriceType] OFF

INSERT INTO [dbo].[PaymentReason] ([Id], [Name]) VALUES (1, N'Электроэнергия')
INSERT INTO [dbo].[PaymentReason] ([Id], [Name]) VALUES (2, N'Автоматический перерасчет')
INSERT INTO [dbo].[PaymentReason] ([Id], [Name]) VALUES (3, N'Ручной перерасчет')
INSERT INTO [dbo].[PaymentReason] ([Id], [Name]) VALUES (4, N'Отключение')
INSERT INTO [dbo].[PaymentReason] ([Id], [Name]) VALUES (5, N'Подключение')
INSERT INTO [dbo].[PaymentReason] ([Id], [Name]) VALUES (6, N'По акту неучтенного потребления')
INSERT INTO [dbo].[PaymentReason] ([Id], [Name]) VALUES (7, N'По нормативам потребления')
INSERT INTO [dbo].[PaymentReason] ([Id], [Name]) VALUES (8, N'Изменение показаний счетчика')
INSERT INTO [dbo].[PaymentReason] ([Id], [Name]) VALUES (9, N'По суду')
INSERT INTO [dbo].[PaymentReason] ([Id], [Name]) VALUES (10, N'Исполнительный лист')
INSERT INTO [dbo].[PaymentReason] ([Id], [Name]) VALUES (11, N'Госпошлина')
INSERT INTO [dbo].[PaymentReason] ([Id], [Name]) VALUES (12, N'Общий счетчик / МОП')
INSERT INTO [dbo].[PaymentReason] ([Id], [Name]) VALUES (256, N'Иные операции')
