//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CashCenter.Common.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.3.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CasherName {
            get {
                return ((string)(this["CasherName"]));
            }
            set {
                this["CasherName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ArticlesWarehouseCode {
            get {
                return ((string)(this["ArticlesWarehouseCode"]));
            }
            set {
                this["ArticlesWarehouseCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ArticlesWarehouseName {
            get {
                return ((string)(this["ArticlesWarehouseName"]));
            }
            set {
                this["ArticlesWarehouseName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ArticlesDocumentNumberCurrentValue {
            get {
                return ((int)(this["ArticlesDocumentNumberCurrentValue"]));
            }
            set {
                this["ArticlesDocumentNumberCurrentValue"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public float WaterСommissionPercent {
            get {
                return ((float)(this["WaterСommissionPercent"]));
            }
            set {
                this["WaterСommissionPercent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int GarbageCollectionFilialCode {
            get {
                return ((int)(this["GarbageCollectionFilialCode"]));
            }
            set {
                this["GarbageCollectionFilialCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public float GarbageCollectionCommissionPercent {
            get {
                return ((float)(this["GarbageCollectionCommissionPercent"]));
            }
            set {
                this["GarbageCollectionCommissionPercent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int RepairFilialCode {
            get {
                return ((int)(this["RepairFilialCode"]));
            }
            set {
                this["RepairFilialCode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public float RepairCommissionPercent {
            get {
                return ((float)(this["RepairCommissionPercent"]));
            }
            set {
                this["RepairCommissionPercent"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ArticlesManipulatorType {
            get {
                return ((int)(this["ArticlesManipulatorType"]));
            }
            set {
                this["ArticlesManipulatorType"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ArticlesZeusDbUrl {
            get {
                return ((string)(this["ArticlesZeusDbUrl"]));
            }
            set {
                this["ArticlesZeusDbUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ArticlesZeusDbPath {
            get {
                return ((string)(this["ArticlesZeusDbPath"]));
            }
            set {
                this["ArticlesZeusDbPath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EnergyPerformerInn {
            get {
                return ((string)(this["EnergyPerformerInn"]));
            }
            set {
                this["EnergyPerformerInn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EnergyPerformerName {
            get {
                return ((string)(this["EnergyPerformerName"]));
            }
            set {
                this["EnergyPerformerName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EnergyPerformerKpp {
            get {
                return ((string)(this["EnergyPerformerKpp"]));
            }
            set {
                this["EnergyPerformerKpp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EnergyReceiverInn {
            get {
                return ((string)(this["EnergyReceiverInn"]));
            }
            set {
                this["EnergyReceiverInn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EnergyReceiverName {
            get {
                return ((string)(this["EnergyReceiverName"]));
            }
            set {
                this["EnergyReceiverName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EnergyReceiverBankName {
            get {
                return ((string)(this["EnergyReceiverBankName"]));
            }
            set {
                this["EnergyReceiverBankName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EnergyReceiverBankBik {
            get {
                return ((string)(this["EnergyReceiverBankBik"]));
            }
            set {
                this["EnergyReceiverBankBik"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string EnergyReceiverAccount {
            get {
                return ((string)(this["EnergyReceiverAccount"]));
            }
            set {
                this["EnergyReceiverAccount"] = value;
            }
        }
    }
}
