//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CashCenter.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class ArticlePrice
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ArticlePrice()
        {
            this.ArticleSale = new HashSet<ArticleSale>();
        }
    
        public int Id { get; set; }
        public int ArticleId { get; set; }
        public int ArticlePriceTypeId { get; set; }
        public System.DateTime EntryDate { get; set; }
        public decimal Value { get; set; }
    
        public virtual Article Article { get; set; }
        public virtual ArticlePriceType ArticlePriceType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ArticleSale> ArticleSale { get; set; }
    }
}
