//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CashCenter.Dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CashCenterEntities : DbContext
    {
        public CashCenterEntities()
            : base("name=CashCenterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Article> Article { get; set; }
        public virtual DbSet<ArticlePrice> ArticlePrice { get; set; }
        public virtual DbSet<ArticlePriceType> ArticlePriceType { get; set; }
        public virtual DbSet<ArticleSale> ArticleSale { get; set; }
    }
}
