//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CashCenter.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class EnergyCustomer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EnergyCustomer()
        {
            this.EnergyCustomerPayments = new HashSet<EnergyCustomerPayment>();
        }
    
        public int Id { get; set; }
        public int DepartmentId { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public int DayValue { get; set; }
        public int NightValue { get; set; }
        public decimal Balance { get; set; }
        public decimal Penalty { get; set; }
        public bool IsActive { get; set; }
        public string Email { get; set; }
        public int Number { get; set; }
        public bool IsClosed { get; set; }
        public string PaymentDocumentIdentifier { get; set; }
        public string HusIdentifier { get; set; }
    
        public virtual Department Department { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnergyCustomerPayment> EnergyCustomerPayments { get; set; }
    }
}
