//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CashCenter.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class GarbageCollectionPayment
    {
        public int Id { get; set; }
        public int FinancialPeriodCode { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int OrganizationCode { get; set; }
        public int FilialCode { get; set; }
        public int CustomerNumber { get; set; }
        public decimal Cost { get; set; }
        public decimal CommissionValue { get; set; }
    }
}
