//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CashCenter.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class WaterCustomerPayment
    {
        public int Id { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int CustomerId { get; set; }
        public double CounterValue1 { get; set; }
        public double CounterValue2 { get; set; }
        public double CounterValue3 { get; set; }
        public double CounterValue4 { get; set; }
        public string Description { get; set; }
        public decimal Penalty { get; set; }
        public decimal Cost { get; set; }
        public int FiscalNumber { get; set; }
    
        public virtual WaterCustomer WaterCustomer { get; set; }
    }
}
