//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CashCenter.Objective.DocumentsReceipt.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiptDocument
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int PaymentsCountSum { get; set; }
        public decimal PaymentsTotalSum { get; set; }
        public int SettlementCenterId { get; set; }
    
        public virtual SettlementCenter SettlementCenter { get; set; }
    }
}
